[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'janx/vim-rubytest'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/tracwiki'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
# fork from 'tomasr/molokai' 
repo = 'sugilog/molokai' 

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'spolu/dwm.vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]]
repo = 'w0rp/ale'
