[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'zhaocai/unite-scriptnames'

[[plugins]]
# fork from 'basyura/unite-rails'
repo = 'sugilog/unite-rails'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/tracwiki'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
# fork from 'tomasr/molokai' 
repo = 'sugilog/molokai' 

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = "osyo-manga/vim-precious"

[[plugins]]
repo = 'benmills/vimux'

[[plugins]]
repo = 'pgr0ss/vimux-ruby-test'

[[plugins]]
repo = 'spolu/dwm.vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

