[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/tracwiki'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
# fork from 'tomasr/molokai' 
repo = 'sugilog/molokai' 

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'zhamlin/tiler.vim'

[[plugins]]
repo = 'thinca/vim-prettyprint'
