autoload -Uz compinit && compinit

for _source in $(ls ~/workspace/github.com/sugilog/dotfiles/zsh/plugins/*)
do
  source ${_source}
done

export LOCAL_PLUG=~/.config/localplug
if [ -d ${LOCAL_PLUG:?} ]
then
  # export HOMEBREW_GITHUB_API_TOKEN=
  # export GITLAB_GLCH_TOKEN=
  source ${LOCAL_PLUG:?}
fi

export PATH="$PATH:/usr/local/opt/mysql@5.6/bin"
