export ZPLUG_HOME=~/.config/zplug-home
export LOCAL_PLUG=~/.config/localplug
source ~/.config/zplug/init.zsh
zplug "plugins/git", from:oh-my-zsh
zplug "knu/z", use:z.sh, defer:2
zplug "~/dotfiles/zsh/plugin", from:local, as:plugin
zplug "~/dotfiles/zsh/theme", from:local, as:theme
zplug "~/dotfiles/zsh/completion", from:local, as:plugin, defer:2
if [ -d ${LOCAL_PLUG:?} ]
then
  # export HOMEBREW_GITHUB_API_TOKEN=
  # export GITLAB_GLCH_TOKEN=
  zplug ${LOCAL_PLUG:?}, from:local, as:plugin
fi
zplug load --verbose
export PATH="$PATH:/usr/local/opt/mysql@5.6/bin"
