export ZPLUG_HOME=~/.config/zplug-home
export LOCAL_PLUG=~/.config/localplug
source ~/.config/zplug/init.zsh
zplug "plugins/git", from:oh-my-zsh
zplug "knu/z", use:z.sh, defer:2
zplug "~/dotfiles/zsh/plugin", from:local, as:plugin
zplug "~/dotfiles/zsh/theme", from:local, as:theme
if [ -d ${LOCAL_PLUG:?} ]
then
  zplug ${LOCAL_PLUG:?}, from:local, as:plugin
fi
zplug load --verbose
